# Generated by Django 3.2.4 on 2021-06-26 10:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=255, unique=True, verbose_name='Название фильма')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Url')),
                ('film_descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('film_main_image', models.ImageField(upload_to='image/film/', verbose_name='Главная картинка')),
                ('image_1', models.ImageField(blank=True, upload_to='image/film/')),
                ('image_2', models.ImageField(blank=True, upload_to='image/film/')),
                ('image_3', models.ImageField(blank=True, upload_to='image/film/')),
                ('image_4', models.ImageField(blank=True, upload_to='image/film/')),
                ('image_5', models.ImageField(blank=True, upload_to='image/film/')),
                ('trailer_link', models.URLField(verbose_name='Ссылка на трейлер')),
                ('type_3D', models.BooleanField(default=False, verbose_name='3D')),
                ('type_2D', models.BooleanField(default=False, verbose_name='2D')),
                ('type_IMAX', models.BooleanField(default=False, verbose_name='IMAX')),
                ('SEO_url', models.URLField(blank=True, verbose_name='URL: ')),
                ('SEO_title', models.CharField(blank=True, max_length=255, verbose_name='Title: ')),
                ('SEO_keywords', models.CharField(blank=True, max_length=255, verbose_name='Keywords: ')),
                ('SEO_description', models.CharField(blank=True, max_length=255, verbose_name='Description: ')),
            ],
        ),
    ]
