# Generated by Django 3.2.4 on 2021-06-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0004_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
    ]
