# Generated by Django 3.2.4 on 2021-06-27 14:27

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0005_alter_user_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_name', models.CharField(max_length=255, unique=True, verbose_name='Название фильма')),
                ('status', models.BooleanField(default=False, verbose_name='Показать')),
                ('news_slug', models.SlugField(max_length=200, unique=True, verbose_name='Url')),
                ('news_descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('news_main_image', models.ImageField(upload_to='image/news/', verbose_name='Главная картинка')),
                ('image_1', models.ImageField(blank=True, upload_to='image/news/')),
                ('image_2', models.ImageField(blank=True, upload_to='image/news/')),
                ('image_3', models.ImageField(blank=True, upload_to='image/news/')),
                ('image_4', models.ImageField(blank=True, upload_to='image/news/')),
                ('image_5', models.ImageField(blank=True, upload_to='image/news/')),
                ('news_link', models.URLField(verbose_name='Ссылка на трейлер')),
                ('published_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('SEO_url', models.URLField(blank=True, verbose_name='URL: ')),
                ('SEO_title', models.CharField(blank=True, max_length=255, verbose_name='Title: ')),
                ('SEO_keywords', models.CharField(blank=True, max_length=255, verbose_name='Keywords: ')),
                ('SEO_description', models.CharField(blank=True, max_length=255, verbose_name='Description: ')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_name', models.CharField(max_length=255, unique=True, verbose_name='Название фильма')),
                ('status', models.BooleanField(default=False, verbose_name='Показать')),
                ('promo_slug', models.SlugField(max_length=200, unique=True, verbose_name='Url')),
                ('promo_descriptions', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('promo_main_image', models.ImageField(upload_to='image/promo/', verbose_name='Главная картинка')),
                ('image_1', models.ImageField(blank=True, upload_to='image/promo/')),
                ('image_2', models.ImageField(blank=True, upload_to='image/promo/')),
                ('image_3', models.ImageField(blank=True, upload_to='image/promo/')),
                ('image_4', models.ImageField(blank=True, upload_to='image/promo/')),
                ('image_5', models.ImageField(blank=True, upload_to='image/promo/')),
                ('promo_link', models.URLField(verbose_name='Ссылка на трейлер')),
                ('published_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('SEO_url', models.URLField(blank=True, verbose_name='URL: ')),
                ('SEO_title', models.CharField(blank=True, max_length=255, verbose_name='Title: ')),
                ('SEO_keywords', models.CharField(blank=True, max_length=255, verbose_name='Keywords: ')),
                ('SEO_description', models.CharField(blank=True, max_length=255, verbose_name='Description: ')),
            ],
        ),
    ]
