# Generated by Django 3.2.4 on 2021-06-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0007_auto_20210627_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateField(blank=True, verbose_name='Дата публикации'),
        ),
    ]
