# Generated by Django 3.2.4 on 2021-06-27 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0009_remove_news_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
