# Generated by Django 3.2.4 on 2021-06-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0012_alter_news_news_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
        migrations.AlterField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(default='df', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_link',
            field=models.URLField(blank=True, verbose_name='Ссылка видео'),
        ),
    ]
