# Generated by Django 3.2.4 on 2021-06-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0013_auto_20210628_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
