# Generated by Django 3.2.4 on 2021-06-28 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminka', '0015_bannersetting_cinemacontact_contactpage_endtoend_mainpage_pages_promotionbanner_topbanner_upperbanne'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='published_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='published_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='pages',
            name='published_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
